# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  #test:
    #docker:
      #- image: hashicorp/terraform:light
        #steps:
      #- checkout
      # Replace this with a real test runner invocation
      #- run:
        #     name: Run tests
            #    command: echo ''
  build-and-deploy-infra:
    docker:
      - image: $ECR_TF_IMAGE
          aws_auth:
            aws_access_key_id: $ECR_AWS_ACCESS_KEY_ID_
            aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY

    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Install and Setup AWS creds
          command: |
              aws configure set region $REGION --profile $PROFILE
              aws configure set aws_access_key_id $ECR_AWS_ACCESS_KEY_ID --profile $PROFILE
              aws configure set aws_secret_access_key $ECR_AWS_SECRET_ACCESS_KEY --profile $PROFILE
              aws configure --profile $PROFILE list
      - run:
          name: terraform init
          command: cd /root/project/.terraform; terraform init
      - run:
          name: terraform plan
          command: cd /root/project/.terraform; terraform plan -out plan.out
      - run:
          name: terraform apply
          command: cd /root/project/.terraform; terraform apply plan.out

  trivy-dependency-scan:
    description: Trivy Vulnerable Scanner  
    docker:
      - image: "aquasec/trivy"
    steps:
      - checkout
      - run:
          name: Install and run Trivy
          command: |
            mkdir -p /tmp/artifacts
            # file system andpackage check
            if trivy fs --scanners vuln,secret,misconfig . > /tmp/artifacts/trivy_report ; then echo "#"; exit 0; else echo "Trivy Run Successfully" exit 0; fi            
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  build-and-deploy-worflow:
    jobs:
      #- test:
      #    filters:
      #      branches:
      #        only:
      #          - /test.*/
      #          - main
      - build-and-deploy-infra:
          requires:
            #     - test
            - trivy-dependency-scan
  
      - trivy-dependency-scan:
          filters:
            branches:
              only:
                - /test.*/
                - main 
